get generate model with assets/models/users.json
get generate model with assets/models/ai_company.json
get generate model with assets/models/ai_model.json
get generate model with assets/models/ai_model_output_data.json
get generate model with assets/models/conversation.json
get generate model with assets/models/question.json
get generate model with assets/models/question_media.json
get generate model with assets/models/answer.json
get generate model with assets/models/app_setting.json
